name: Release Docker

on:
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    buildSnap:
    environment: snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

      - name: Update snapcraft version file
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = strenv(VERSION)' snap/snapcraft.yaml
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge